### ISSUE TITLE
Error Handling - Async Await 

### ISSUE THREAD

**Issue by vitorveiga** [Checkmarx/JS-SCP#3]
Hi again,

By the way, amazing guideline. On Error handling section, says that "With the release of ES6, async / await allows developers...", buy async/await feature belongs in fact to ES2017 specification.

Best Regards

**Comment by PauloASilva** [comment]
Hi @vitorveiga,
You're right, we should say ES8/ES2017.

I will fix it soon.

Thanks,
Paulo A. Silva
