### ISSUE TITLE
Dead read links

### ISSUE THREAD

**Issue by kospl** [Checkmarx/JS-SCP#5]
Hi, is this project in active development?

All links to read (first paragraph of readme) are leading to 404.

**Comment by ErezYalon** [comment]
Thanks for noticing @kospl.
We will soon move it to GitHub Pages and fix the links.

**Comment by iamraviprakash** [comment]
@PauloASilva @ErezYalon Are there any updates on dead links?

**Comment by PauloASilva** [comment]
Hi @iamraviprakash,

> @PauloASilva @ErezYalon Are there any updates of dead links?

Not really.

What would you like the most: the PDF/MOBI/ePub version or being able to read it online (e.g. [Kotlin SCP](https://checkmarx.github.io/Kotlin-SCP)) ?

Cheers,
Paulo A. Silva

**Comment by iamraviprakash** [comment]
@PauloASilva PDF would be better

**Comment by PauloASilva** [comment]
Hi @iamraviprakash,
You should now be able to access/download PDF, MOBI and ePUB from the README. Hope you enjoy it!

Cheers,
Paulo A. Silva
